/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlcb;

//import com.mysql.cj.jdbc.result.ResultSetMetaData;
// Them thu vien cho cac chuc nang
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Connection;
import java.text.MessageFormat;
import java.util.regex.PatternSyntaxException;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author phuocnhat
 */
public class Customer1 extends javax.swing.JFrame {
    /**
     * Creates new form Customer1
     */
    //Tao bien de lien ket csdl
    private static final String username = "root";
    private static final String passw = "phuocnhat";
    private static final String link = "jdbc:mysql://localhost:3306/bigwork";
    
    double value;
    double fnum;
    double snum;
    double ans;
    Connection sqlBTL = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    
    public Customer1() {
        initComponents();
        upDateDB();
        
        
    }
    
    
//Cai linear color cho thanh menu
class jPanelGradient extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
          
            Color color1 = new Color(41, 241, 195);
            Color color2 = new Color(27, 163, 156);
            GradientPaint gp = new GradientPaint(0, 0, color1, 45, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

//Cai linear color cho panel chinh

class jPanelGradient1 extends JPanel{
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
          
            Color color1 = new Color(103, 230, 215);
            Color color2 = new Color(255,255,255);
            GradientPaint gp = new GradientPaint(0, 0, color1, 45, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    
//==================update=====================
//CAP NHAT LAI THONG TIN KHACH HANG
public void upDateDB(){
    try{
           
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            sqlBTL = DriverManager.getConnection(link,username,passw);
            ps = sqlBTL.prepareStatement("select * from BTLON");
            
            rs = ps.executeQuery();
            ResultSetMetaData StData = rs.getMetaData();            
            q = StData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)tableCtm.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                
                Vector columnData = new Vector();
                
                for ( i = 1; i <= q; i++)
                {
                   columnData.add(rs.getString("IDKH"));
                   columnData.add(rs.getString("HOTEN"));
                   columnData.add(rs.getString("GiOITINH"));
                   columnData.add(rs.getString("CMND"));
                   columnData.add(rs.getString("DTHOAI"));
                   columnData.add(rs.getString("DCHI"));
                   columnData.add(rs.getString("SLVE"));
                   columnData.add(rs.getString("LOAIVE"));
                   columnData.add(rs.getString("DIEMDI"));
                   columnData.add(rs.getString("DIEMDEN"));
                   columnData.add(rs.getString("THANHTIEN"));
                   
                }
                    RecordTable.addRow(columnData);                
                
            }
         
        }
        catch (Exception ex) {
            //java.util.logging.Logger.getLogger(Customer1.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, ex);
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelGradient1();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FieldName = new javax.swing.JTextField();
        FieldPhone = new javax.swing.JTextField();
        FieldAddre = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        BtnReset = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CBG = new javax.swing.JComboBox<>();
        FieldIDC = new javax.swing.JTextField();
        NoTicket = new javax.swing.JLabel();
        Types = new javax.swing.JLabel();
        CBG2 = new javax.swing.JComboBox<>();
        FieldTickets = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CBG3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CBG4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        FieldTotal = new javax.swing.JTextField();
        jPanel2 = new jPanelGradient();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnLogOut = new javax.swing.JButton();
        BtnBill = new javax.swing.JButton();
        BtnCustomer1 = new javax.swing.JButton();
        BtnAir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCtm = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TICKET MANAGEMENT");
        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(908, 513));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kindly fill out all the information to complete ticket"));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Full name:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("ID Card:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Address:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Phone:");

        BtnSave.setBackground(new java.awt.Color(255, 255, 255));
        BtnSave.setText("Add");
        BtnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnSaveMouseExited(evt);
            }
        });
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnReset.setBackground(new java.awt.Color(255, 255, 255));
        BtnReset.setText("Reset");
        BtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnResetMouseExited(evt);
            }
        });
        BtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnResetActionPerformed(evt);
            }
        });

        BtnDelete.setBackground(new java.awt.Color(255, 255, 255));
        BtnDelete.setText("Delete");
        BtnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnDeleteMouseExited(evt);
            }
        });
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setText("Update");
        BtnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnUpdateMouseExited(evt);
            }
        });
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Gender:");

        CBG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other", "Male", "Female", " " }));

        NoTicket.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        NoTicket.setText("Number of tickets:");

        Types.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        Types.setText("Types:");

        CBG2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Other", "Low cost", "VIP", " " }));

        FieldTickets.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldTicketsKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Leaving from:");

        CBG3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[..]", "TP. HCM", "Da Nang", "Ha Noi", "Binh Thuan", "Can Tho", "Ben Tre" }));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setText("Going to:");

        CBG4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[..]", "TP. HCM", "Da Nang", "Ha Noi", "Binh Thuan", "Can Tho", "Ben Tre" }));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setText("TOTAL: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldName)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NoTicket)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldTickets)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Types)
                                .addGap(18, 18, 18)
                                .addComponent(CBG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FieldIDC)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(28, 28, 28)
                                .addComponent(CBG3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(26, 26, 26)
                                .addComponent(FieldTotal)
                                .addGap(18, 18, 18)
                                .addComponent(BtnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(CBG4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnReset)
                                .addGap(18, 18, 18)
                                .addComponent(BtnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnUpdate)))
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FieldPhone)
                            .addComponent(FieldAddre))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NoTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Types, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldTickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FieldIDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(FieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FieldAddre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CBG3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CBG4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnReset)
                            .addComponent(BtnDelete)
                            .addComponent(BtnUpdate)
                            .addComponent(BtnSave)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(FieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(210, 400));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1airplane-11-128.png"))); // NOI18N
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        BtnLogOut.setFont(new java.awt.Font("Luminari", 0, 18)); // NOI18N
        BtnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.jpg"))); // NOI18N
        BtnLogOut.setText("Log out");
        BtnLogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnLogOut.setPreferredSize(new java.awt.Dimension(105, 29));
        BtnLogOut.setSize(new java.awt.Dimension(105, 29));
        BtnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLogOutMouseExited(evt);
            }
        });
        BtnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogOutActionPerformed(evt);
            }
        });

        BtnBill.setBackground(new java.awt.Color(255, 255, 255));
        BtnBill.setFont(new java.awt.Font("Luminari", 0, 18)); // NOI18N
        BtnBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bill.jpg"))); // NOI18N
        BtnBill.setText("Revenue");
        BtnBill.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnBill.setPreferredSize(new java.awt.Dimension(105, 29));
        BtnBill.setSize(new java.awt.Dimension(105, 29));
        BtnBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnBillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnBillMouseExited(evt);
            }
        });
        BtnBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBillActionPerformed(evt);
            }
        });

        BtnCustomer1.setBackground(new java.awt.Color(255, 255, 255));
        BtnCustomer1.setFont(new java.awt.Font("Luminari", 0, 18)); // NOI18N
        BtnCustomer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ctm.jpg"))); // NOI18N
        BtnCustomer1.setText("Customer");
        BtnCustomer1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnCustomer1.setSize(new java.awt.Dimension(105, 29));
        BtnCustomer1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCustomer1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCustomer1MouseExited(evt);
            }
        });
        BtnCustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCustomer1ActionPerformed(evt);
            }
        });

        BtnAir.setBackground(new java.awt.Color(255, 255, 255));
        BtnAir.setFont(new java.awt.Font("Luminari", 2, 18)); // NOI18N
        BtnAir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/airline.jpg"))); // NOI18N
        BtnAir.setText("Airline");
        BtnAir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnAir.setSize(new java.awt.Dimension(105, 29));
        BtnAir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnAirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnAirMouseExited(evt);
            }
        });
        BtnAir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BtnBill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCustomer1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnAir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnBill, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableCtm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Full name", "Gender", "ID Card", "Phone", "Address", "Number of tickets", "Types", "Leaving", "Going", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCtm.setFocusable(false);
        tableCtm.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableCtm.setSelectionBackground(new java.awt.Color(153, 255, 255));
        tableCtm.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableCtm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCtmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCtm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 454, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    //THIET LAP CHUC NANG CHO NUT RESET
    private void BtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnResetActionPerformed
        // TODO add your handling code here:
        FieldName.setText("");
        FieldIDC.setText("");
        FieldAddre.setText("");
        FieldPhone.setText("");
        CBG.setSelectedItem("Other");
        CBG2.setSelectedItem("Other");
        CBG3.setSelectedItem("[..]");
        CBG4.setSelectedItem("[..]");
        FieldTickets.setText("");
        FieldTotal.setText("");
    }//GEN-LAST:event_BtnResetActionPerformed
    // Push data to server
    
    //THIET LAP CHUC NANG CHO NUT ADD... DUA DU LIEU LEN DATABASE
    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
        try{
           
            Class.forName("com.mysql.cj.jdbc.Driver"); 
            sqlBTL = DriverManager.getConnection(link, username, passw);
            ps = sqlBTL.prepareStatement("insert into BTLON ( HOTEN, GIOITINH, CMND, DTHOAI, DCHI, DIEMDI, DIEMDEN, LOAIVE, SLVE, THANHTIEN)"
                    + "value( ?, ?, ?, ?, ?, ?, ?,?,?,?)" );

            
            ps.setString(1, FieldName.getText());
            ps.setString(2, (String) CBG.getSelectedItem());
            ps.setString(3, FieldIDC.getText());
            ps.setString(4, FieldPhone.getText());
            ps.setString(5, FieldAddre.getText());
            ps.setString(6, (String) CBG3.getSelectedItem());
            ps.setString(7, (String) CBG4.getSelectedItem());
            ps.setString(8, (String) CBG2.getSelectedItem());
            ps.setString(9, FieldTickets.getText());
            ps.setString(10, FieldTotal.getText());
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Done" );
            upDateDB();
            
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer1.class.getName()).log(java.util.logging.Level.SEVERE, 
                    null, ex);
        } catch (SQLException ex) {
             //System.err.println(ex);
            java.util.logging.Logger.getLogger(Customer1.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } 
        FieldName.setText("");
        FieldIDC.setText("");
        FieldAddre.setText("");
        FieldPhone.setText("");
        CBG.setSelectedItem("Other");
        CBG2.setSelectedItem("Other");
        CBG3.setSelectedItem("[..]");
        CBG4.setSelectedItem("[..]");
        FieldTickets.setText("");
        FieldTotal.setText("");


    }//GEN-LAST:event_BtnSaveActionPerformed

    //TAO HIEU UNG HOVER CHO NUT DELETE
    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)tableCtm.getModel();
        int SelectedRows = tableCtm.getSelectedRow();
        
        try
        {
                    id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
                  
                   deleteItem = JOptionPane.showConfirmDialog(null,"Confirm if you want to delete item",
                   "Warning",JOptionPane.YES_NO_OPTION);
             if (deleteItem ==JOptionPane.YES_OPTION ) 
             {                 
         
           Class.forName("com.mysql.cj.jdbc.Driver"); 
            sqlBTL = DriverManager.getConnection(link,username,passw);
                ps = sqlBTL.prepareStatement("delete from BTLON where IDKH =?");
                
               ps.setInt(1, id);
               ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Record updated");
            upDateDB();
            
            FieldName.setText("");
            FieldIDC.setText("");
            FieldAddre.setText("");
            FieldPhone.setText("");
            CBG.setSelectedItem("Other");
            CBG2.setSelectedItem("Other");
            CBG3.setSelectedItem("[..]");
            CBG4.setSelectedItem("[..]");
            FieldTickets.setText("");
            FieldTotal.setText("");
            
             }
           
        }
        
        catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(Customer1.class.getName()).log(java.util.logging.Level.SEVERE, 
           null, ex);
        } catch (SQLException ex) {
             System.err.println(ex);

        } 
    }//GEN-LAST:event_BtnDeleteActionPerformed
    //THIET LAP CHUC NANG UPDATE
    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)tableCtm.getModel();
        int SelectedRows = tableCtm.getSelectedRow();
        
        try
        {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlBTL = DriverManager.getConnection(link,username,passw);
            String SQL = "update BTLON set HOTEN=?, GIOITINH=?, CMND=?, DTHOAI=?, DCHI=?, DIEMDI=?, DIEMDEN=?, LOAIVE=?, SLVE=?, THANHTIEN=? where IDKH = " + tableCtm.getValueAt(SelectedRows, 0) + ";";
            ps = sqlBTL.prepareCall(SQL);
            
            ps.setString(1, FieldName.getText());
            ps.setString(2, (String) CBG.getSelectedItem());
            ps.setString(3, FieldIDC.getText());
            ps.setString(4, FieldPhone.getText());
            ps.setString(5, FieldAddre.getText());
            ps.setString(6, (String) CBG3.getSelectedItem());
            ps.setString(7, (String) CBG4.getSelectedItem());
            ps.setString(8, (String) CBG2.getSelectedItem());
            ps.setString(9, FieldTickets.getText());
            ps.setString(10, FieldTotal.getText());
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");
            upDateDB();
        }
        
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer1.class.getName()).log(java.util.logging.Level.SEVERE, 
           null, ex);
        } catch (SQLException ex) {
             System.err.println(ex);
        } 
    }//GEN-LAST:event_BtnUpdateActionPerformed
//HIEN THI DU LIEU TRONG TABLE
    private void tableCtmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCtmMouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)tableCtm.getModel();
        int SelectedRows = tableCtm.getSelectedRow();
        FieldName.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        CBG.setSelectedItem(RecordTable.getValueAt(SelectedRows, 2).toString());
        FieldIDC.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        FieldPhone.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        FieldAddre.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        FieldTickets.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
        CBG2.setSelectedItem(RecordTable.getValueAt(SelectedRows, 7).toString());
        CBG3.setSelectedItem(RecordTable.getValueAt(SelectedRows, 8).toString());
        CBG4.setSelectedItem(RecordTable.getValueAt(SelectedRows, 9).toString());
        FieldTotal.setText(RecordTable.getValueAt(SelectedRows, 10).toString());
        
    }//GEN-LAST:event_tableCtmMouseClicked
//TAO HIEU UNG HOVER CHO NUT ADD
    private void BtnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSaveMouseEntered
        // TODO add your handling code here:
        BtnSave.setBackground(new Color(148,239,236));
    }//GEN-LAST:event_BtnSaveMouseEntered
//TAO HIEU UNG HOVER CHO NUT ADD
    private void BtnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSaveMouseExited
        // TODO add your handling code here:
        BtnSave.setBackground(new Color(238,238,238));
        
    }//GEN-LAST:event_BtnSaveMouseExited
//TAO HIEU UNG HOVER CHO NUT RESET
    private void BtnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResetMouseEntered
        // TODO add your handling code here
        BtnReset.setBackground(new Color(148,239,236));
    }//GEN-LAST:event_BtnResetMouseEntered
//TAO HIEU UNG HOVER CHO NUT RESET
    private void BtnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnResetMouseExited
        // TODO add your handling code here:
        BtnReset.setBackground(new Color(238,238,238));

    }//GEN-LAST:event_BtnResetMouseExited
//TAO HIEU UNG HOVER CHO NUT DELETE
    private void BtnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDeleteMouseEntered
        // TODO add your handling code here:
        BtnDelete.setBackground(new Color(148,239,236));        
    }//GEN-LAST:event_BtnDeleteMouseEntered
//TAO HIEU UNG HOVER CHO NUT DELETE
    private void BtnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDeleteMouseExited
        // TODO add your handling code here:
        BtnDelete.setBackground(new Color(238,238,238));        
    }//GEN-LAST:event_BtnDeleteMouseExited
//TAO HIEU UNG HOVER CHO NUT UPDATE
    private void BtnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUpdateMouseEntered
        // TODO add your handling code here:
        BtnUpdate.setBackground(new Color(148,239,236));                
    }//GEN-LAST:event_BtnUpdateMouseEntered
//TAO HIEU UNG HOVER CHO NUT UPDATE
    private void BtnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUpdateMouseExited
        // TODO add your handling code here:\
         BtnUpdate.setBackground(new Color(238,238,238));       
    }//GEN-LAST:event_BtnUpdateMouseExited
//TINH TONG TIEN VE
    private void FieldTicketsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldTicketsKeyReleased
        // TODO add your handling code here:
        value = 0;
        if(CBG2.getSelectedItem().equals("VIP")){
            value = (Double.parseDouble(FieldTickets.getText())*20000);
            FieldTotal.setText(String.valueOf(value));
        }else{ 
            value = (Double.parseDouble(FieldTickets.getText())*10000);
            FieldTotal.setText(String.valueOf(value));
        }
    }//GEN-LAST:event_FieldTicketsKeyReleased
//TAO HIEU UNG HOVER CHO NUT LOGOUT BEN MENU
    private void BtnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogOutMouseEntered
        // TODO add your handling code here:
        BtnLogOut.setBackground(new Color(148,239,236));
    }//GEN-LAST:event_BtnLogOutMouseEntered
//TAO HIEU UNG HOVER CHO NUT LOGOUT BEN MENU
    private void BtnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogOutMouseExited
        // TODO add your handling code here:
        BtnLogOut.setBackground(new Color(238,238,238));
    }//GEN-LAST:event_BtnLogOutMouseExited
//CHUYEN FRAME LOGIN
    private void BtnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogOutActionPerformed
        // TODO add your handling code here:
        Login menu = new Login();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnLogOutActionPerformed

//TAO HIEU UNG HOVER CHO NUT REVENUE BEN MENU

    private void BtnBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBillMouseEntered
        // TODO add your handling code here:
        BtnBill.setBackground(new Color(148,239,236));
    }//GEN-LAST:event_BtnBillMouseEntered
//TAO HIEU UNG HOVER CHO NUT REVENUE BEN MENU

    private void BtnBillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBillMouseExited
        // TODO add your handling code here:
        BtnBill.setBackground(new Color(238,238,238));
    }//GEN-LAST:event_BtnBillMouseExited
//CHUYEN FRAME REVENUE
    private void BtnBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBillActionPerformed
        // TODO add your handling code here:
        Revenue menu = new Revenue();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBillActionPerformed
//TAO HIEU UNG HOVER CHO NUT CUSTOMER BEN MENU

    private void BtnCustomer1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCustomer1MouseEntered
        // TODO add your handling code here:
        BtnCustomer1.setBackground(new Color(148,239,236));
    }//GEN-LAST:event_BtnCustomer1MouseEntered
////TAO HIEU UNG HOVER CHO NUT CUSTOMER BEN MENU

    private void BtnCustomer1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCustomer1MouseExited
        // TODO add your handling code here:
        BtnCustomer1.setBackground(new Color(238,238,238));
    }//GEN-LAST:event_BtnCustomer1MouseExited

    private void BtnCustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCustomer1ActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_BtnCustomer1ActionPerformed
//TAO HIEU UNG HOVER CHO NUT AIRLINE BEN MENU

    private void BtnAirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAirMouseEntered
        // TODO add your handling code here:
        BtnAir.setBackground(new Color(148,239,236));
    }//GEN-LAST:event_BtnAirMouseEntered

    //TAO HIEU UNG HOVER CHO NUT REVENUE BEN MENU

    private void BtnAirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAirMouseExited
        // TODO add your handling code here:
        BtnAir.setBackground(new Color(238,238,238));
    }//GEN-LAST:event_BtnAirMouseExited

    private void BtnAirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAir;
    private javax.swing.JButton BtnBill;
    private javax.swing.JButton BtnCustomer1;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnLogOut;
    private javax.swing.JButton BtnReset;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JComboBox<String> CBG;
    private javax.swing.JComboBox<String> CBG2;
    private javax.swing.JComboBox<String> CBG3;
    private javax.swing.JComboBox<String> CBG4;
    private javax.swing.JTextField FieldAddre;
    private javax.swing.JTextField FieldIDC;
    private javax.swing.JTextField FieldName;
    private javax.swing.JTextField FieldPhone;
    private javax.swing.JTextField FieldTickets;
    public javax.swing.JTextField FieldTotal;
    private javax.swing.JLabel NoTicket;
    private javax.swing.JLabel Types;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tableCtm;
    // End of variables declaration//GEN-END:variables
}
