/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlcb;
import java.util.*;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import javax.swing.border.Border;
//import javax.swing.UIManager;
//import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author phuocnhat
 */
public class Login extends javax.swing.JFrame {

    private static void MyButton() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void Mybutton() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    /**
     * Creates new form Login
     */
    class jPanelGradient extends JPanel{
        @Override
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
          
            Color color1 = new Color(41, 241, 195);
            Color color2 = new Color(27, 163, 156);
            GradientPaint gp = new GradientPaint(0, 0, color1, 90, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
    public Login() {
        initComponents();
       // ttt();

    };
    
    
    /*public void ttt() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(BtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(BtnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        labeluser = new javax.swing.JLabel();
        labelpass = new javax.swing.JLabel();
        Fielduser = new javax.swing.JTextField();
        Fieldpass = new javax.swing.JPasswordField();
        BtnLog = new javax.swing.JButton();
        ShowPass = new javax.swing.JRadioButton();
        jPanel1 = new jPanelGradient();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("HỆ THỐNG BÁN VÉ");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jCheckBox1.setText("Ghi nhớ mật khẩu");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AIRLINE TICKET MANAGEMENT SYSTEM\n");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeluser.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        labeluser.setText("Username:");
        labeluser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                labeluserFocusLost(evt);
            }
        });
        getContentPane().add(labeluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 123, -1, -1));

        labelpass.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        labelpass.setText("Password:");
        getContentPane().add(labelpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 188, -1, -1));

        Fielduser.setForeground(new java.awt.Color(204, 204, 204));
        Fielduser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FielduserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FielduserFocusLost(evt);
            }
        });
        getContentPane().add(Fielduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 120, 237, -1));

        Fieldpass.setCaretColor(new java.awt.Color(204, 204, 204));
        Fieldpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldpassFocusLost(evt);
            }
        });
        getContentPane().add(Fieldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 185, 237, -1));

        BtnLog.setBackground(new java.awt.Color(255, 255, 255));
        BtnLog.setFont(new java.awt.Font("Muna", 1, 24)); // NOI18N
        BtnLog.setText("Login");
        BtnLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 233, 234), 2));
        BtnLog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnLogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnLogMouseExited(evt);
            }
        });
        BtnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 140, 40));

        ShowPass.setText("Show password");
        ShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassActionPerformed(evt);
            }
        });
        getContentPane().add(ShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 217, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 181, 204));

        jLabel4.setFont(new java.awt.Font("Chalkboard SE", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TICKET MANAGEMENT\n");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 431, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == ShowPass) {
            if (ShowPass.isSelected()) {
                Fieldpass.setEchoChar((char) 0);
            } else {
                Fieldpass.setEchoChar('*');
            }
        }
    }//GEN-LAST:event_ShowPassActionPerformed

    private void BtnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogActionPerformed
        // TODO add your handling code here:

        if (evt.getSource() == BtnLog) {
            String userText;
            String pwdText;
            userText = Fielduser.getText();
            pwdText = Fieldpass.getText();
            if (userText.equalsIgnoreCase("admin") && pwdText.equalsIgnoreCase("12345")) {
                //JOptionPane.showMessageDialog(this, "Successed login!!!");
                AirlineADS menu = new AirlineADS();
                menu.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Incorrect username or password ", "ERROR ", JOptionPane.ERROR_MESSAGE);
//              JOptionPane.Error_Message(this, "Tài khoản hoặc mật khẩu không đúng");
            }

        }
    }//GEN-LAST:event_BtnLogActionPerformed

    private void BtnLogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogMouseEntered
        // TODO add your handling code here:
         BtnLog.setBackground(new Color(148,239,236));
    }//GEN-LAST:event_BtnLogMouseEntered

    private void BtnLogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLogMouseExited
        // TODO add your handling code here:
        BtnLog.setBackground(new Color(238,238,238));
    }//GEN-LAST:event_BtnLogMouseExited

    private void FielduserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FielduserFocusGained
        // TODO add your handling code here:
         if(Fielduser.getText().trim().toLowerCase().equals("username"))
        {
            Fielduser.setText("");
            Fielduser.setForeground(Color.black);
        }
        
        //set border for label_user
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.cyan);
        labeluser.setBorder(label_border);

        
    }                                    

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {                                   
        
        //if the text is "username" or empty
        //set the text is "username"
        if(Fielduser.getText().trim().equals("") || 
           Fielduser.getText().trim().toLowerCase().equals("username"))
        {
            Fielduser.setText("username");
            Fielduser.setForeground(new Color(153,153,153));
        }
        
        //remove border from label_user
        labeluser.setBorder(null);

    }//GEN-LAST:event_FielduserFocusGained

    private void labeluserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_labeluserFocusLost
        // TODO add your handling code here:
         if(labeluser.getText().trim().equals("") || 
           labeluser.getText().trim().toLowerCase().equals("username"))
        {
            labeluser.setText("username");
            labeluser.setForeground(new Color(153,153,153));
        }
        
        //remove border from label_user
        labeluser.setBorder(null);
        

    }//GEN-LAST:event_labeluserFocusLost

    private void FieldpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldpassFocusGained
        // TODO add your handling code here:
         String pas = String.valueOf(Fieldpass.getPassword());
        
        if(pas.trim().toLowerCase().equals("password"))
        {
            Fieldpass.setText("");
            Fieldpass.setForeground(Color.black);
        }
        
        //set border for label_pass
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.cyan);
        labelpass.setBorder(label_border);

    }//GEN-LAST:event_FieldpassFocusGained

    private void FieldpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldpassFocusLost
        // TODO add your handling code here:
         String pas = String.valueOf(Fieldpass.getPassword());
        
        if(pas.trim().equals("") || pas.trim().toLowerCase().equals("password"))
        {
            Fieldpass.setText("password");
            Fieldpass.setForeground(new Color(153,153,153));
        }
        
        //remove border from label_user
        labelpass.setBorder(null);

    }//GEN-LAST:event_FieldpassFocusLost

    private void FielduserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FielduserFocusLost
        // TODO add your handling code here:
         if(Fielduser.getText().trim().equals("") || 
           Fielduser.getText().trim().toLowerCase().equals("username"))
        {
            Fielduser.setText("username");
            Fielduser.setForeground(new Color(153,153,153));
        }
        
        //remove border from label_user
        labeluser.setBorder(null);

    }//GEN-LAST:event_FielduserFocusLost
private JFrame frame;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        //MyButton();
//throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //Round Button: 
       // UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");

        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLog;
    private javax.swing.JPasswordField Fieldpass;
    private javax.swing.JTextField Fielduser;
    private javax.swing.JRadioButton ShowPass;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelpass;
    private javax.swing.JLabel labeluser;
    // End of variables declaration//GEN-END:variables
}
